[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Turbulox = "25c03aae-1219-43c4-862d-5fc87f57ed09"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[sources]
Turbulox = {path = ".."}

[compat]
CUDA = "5"
CairoMakie = "0.13"
GLMakie = "0.11"
Infiltrator = "1"
LinearAlgebra = "1"
Random = "1"
StaticArrays = "1"
WGLMakie = "0.11"
julia = "1"

[extras]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
